### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by filipinyo** [vabatta/omx-manager#3] opened 2015-08-27 10:11 UTC
Hey there. I'm using your manager and the only problem I have is when I try to handle error which occurs if file which I'm trying to play is not good.

Does your omx.play handle errors? I can't make it work.

PS: I'm quite fresh with node

**Comment by vabatta** [comment] 2015-09-16 23:25
Hi! Yes, most of the errors are handled but some aren't reported. The error you're asking for could be checked with `omx-player` or with other tools / libraries?

**Comment by sy1vain** [comment] 2016-05-10 15:09
Could it be caused by the 'play' function being empty. If  call _startup on an instance it works!

**Comment by vabatta** [comment] 2016-05-10 23:15
Which version are you using?

**Comment by sy1vain** [comment] 2016-05-11 08:35
Version 0.1.1

It seems to me that this is the mapped function for the play command:

https://github.com/vabatta/omx-manager/blob/f8706aedc9ff41b6dfb739bf470b0e386318f5b6/lib/omxinstance.js#L182-L183

In that case, it will never call anything on play, but will on _startup: https://github.com/vabatta/omx-manager/blob/f8706aedc9ff41b6dfb739bf470b0e386318f5b6/lib/omxinstance.js#L102

**Comment by vabatta** [comment] 2016-05-11 10:04
Okay, this should be fixed with `0.1.2`. Run `npm update` to get it.
The actual implementation of the `OmxInstance` is in the class named `Controller` at the end, because it's an abstract class.
Look at the code in `development` branch.

**Comment by sy1vain** [comment] 2016-05-11 10:15
Works for me!

**Closed as completed** 2016-06-09 00:16 UTC
